/**
 * This file auto-generated by Fern from our API Definition.
 */

import { DopplerApi } from "../../..";

export interface ActivityLog {
  /** Unique identifier for the object. */
  id: string;
  /** Text describing the event. */
  text: string;
  /** HTML describing the event. */
  html: string;
  user: DopplerApi.activityLog.User;
  /** Unique identifier for the project object. */
  project: string;
  /** Unique identifier for the environment object. */
  environment: string;
  /** The config's name. */
  config: string;
  /** Date and time of the object's creation. */
  createdAt: Date;
}
