/**
 * This file auto-generated by Fern from our API Definition.
 */

import { DopplerApi } from "../../..";

export interface ActivityLogsList {
  page: number;
  logs: DopplerApi.activityLog.ActivityLog[];
}
