/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface UpdateWorkplace {
  /** Name of the workplace. */
  name?: string;
  /** Billing email we will send invoices to. */
  billingEmail?: string;
}
