/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface Workplace {
  /** Name of the workplace. */
  name: string;
  /** Billing email we will send invoices to. */
  billingEmail: string;
}
