/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface CreateProjectRequest {
  /** Name of project */
  name: string;
  /** Description of project */
  description?: string;
}
