/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface Project {
  /** Unique identifier for the object. */
  id: string;
  /** Name of the project. */
  name: string;
  /** Description of the project. */
  description: string;
  /** Date and time of the object's creation. */
  createdAt: Date;
}
