/**
 * This file auto-generated by Fern from our API Definition.
 */

export interface UpdateProjectRequest {
  /** Unique identifier for the project object. */
  project: string;
  /** Name of the project. */
  name: string;
  /** Description of the project. */
  description?: string;
}
