/**
 * This file auto-generated by Fern from our API Definition.
 */

import { DopplerApi } from "../../..";
import * as core from "../../../core";

export const CreateProjectRequest: core.schemas.ObjectSchema<
  CreateProjectRequest.Raw,
  DopplerApi.projects.CreateProjectRequest
> = core.schemas.object({
  name: core.schemas.string(),
  description: core.schemas.string().optional(),
});

export declare namespace CreateProjectRequest {
  interface Raw {
    name: string;
    description?: string | null;
  }
}
