/**
 * This file auto-generated by Fern from our API Definition.
 */

import { DopplerApi } from "../../..";
import * as core from "../../../core";

export const DeleteProjectRequest: core.schemas.ObjectSchema<
  DeleteProjectRequest.Raw,
  DopplerApi.projects.DeleteProjectRequest
> = core.schemas.object({
  project: core.schemas.string(),
});

export declare namespace DeleteProjectRequest {
  interface Raw {
    project: string;
  }
}
