/**
 * This file auto-generated by Fern from our API Definition.
 */

import { DopplerApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const ProjectList: core.schemas.ObjectSchema<ProjectList.Raw, DopplerApi.projects.ProjectList> =
  core.schemas.object({
    page: core.schemas.number(),
    projects: core.schemas.list(core.schemas.lazyObject(() => serializers.projects.Project)),
  });

export declare namespace ProjectList {
  interface Raw {
    page: number;
    projects: serializers.projects.Project.Raw[];
  }
}
