/**
 * This file auto-generated by Fern from our API Definition.
 */

import { DopplerApi } from "../../..";
import * as core from "../../../core";

export const Project: core.schemas.ObjectSchema<Project.Raw, DopplerApi.projects.Project> = core.schemas.object({
  id: core.schemas.string(),
  name: core.schemas.string(),
  description: core.schemas.string(),
  createdAt: core.schemas.property("created_at", core.schemas.date()),
});

export declare namespace Project {
  interface Raw {
    id: string;
    name: string;
    description: string;
    created_at: string;
  }
}
