/**
 * This file auto-generated by Fern from our API Definition.
 */

import { DopplerApi } from "../../..";
import * as core from "../../../core";
import * as serializers from "../..";

export const ActivityLog: core.schemas.ObjectSchema<ActivityLog.Raw, DopplerApi.activityLog.ActivityLog> =
  core.schemas.object({
    id: core.schemas.string(),
    text: core.schemas.string(),
    html: core.schemas.string(),
    user: core.schemas.lazyObject(() => serializers.activityLog.User),
    project: core.schemas.string(),
    environment: core.schemas.string(),
    config: core.schemas.string(),
    createdAt: core.schemas.property("created_at", core.schemas.date()),
  });

export declare namespace ActivityLog {
  interface Raw {
    id: string;
    text: string;
    html: string;
    user: serializers.activityLog.User.Raw;
    project: string;
    environment: string;
    config: string;
    created_at: string;
  }
}
