/**
 * This file auto-generated by Fern from our API Definition.
 */

import { DopplerApi } from "../../..";
import * as core from "../../../core";

export const User: core.schemas.ObjectSchema<User.Raw, DopplerApi.activityLog.User> = core.schemas.object({
  email: core.schemas.string(),
  name: core.schemas.string(),
  profileImageUrl: core.schemas.property("profile_image_url", core.schemas.string()),
});

export declare namespace User {
  interface Raw {
    email: string;
    name: string;
    profile_image_url: string;
  }
}
