/**
 * This file auto-generated by Fern from our API Definition.
 */

import { DopplerApi } from "../../..";
import * as core from "../../../core";

export const RevokeRequest: core.schemas.ObjectSchema<RevokeRequest.Raw, DopplerApi.auth.RevokeRequest> =
  core.schemas.object({
    token: core.schemas.string(),
  });

export declare namespace RevokeRequest {
  interface Raw {
    token: string;
  }
}
