/**
 * This file auto-generated by Fern from our API Definition.
 */

export const Environment = {
  Production: "https://api.doppler.com/v3",
} as const;

export type Environment = typeof Environment.Production;
