/**
 * This file auto-generated by Fern from our API Definition.
 */

import { DopplerApi } from "../../..";
import * as core from "../../../core";

export const UpdateWorkplace: core.schemas.ObjectSchema<UpdateWorkplace.Raw, DopplerApi.workplace.UpdateWorkplace> =
  core.schemas.object({
    name: core.schemas.string().optional(),
    billingEmail: core.schemas.property("billing_email", core.schemas.string().optional()),
  });

export declare namespace UpdateWorkplace {
  interface Raw {
    name?: string | null;
    billing_email?: string | null;
  }
}
