/**
 * This file auto-generated by Fern from our API Definition.
 */

import { DopplerApi } from "../../..";
import * as core from "../../../core";

export const Workplace: core.schemas.ObjectSchema<Workplace.Raw, DopplerApi.workplace.Workplace> = core.schemas.object({
  name: core.schemas.string(),
  billingEmail: core.schemas.property("billing_email", core.schemas.string()),
});

export declare namespace Workplace {
  interface Raw {
    name: string;
    billing_email: string;
  }
}
